{"name": "Проверка возвращаемого кода 409 при создании курьера с уже существующими данными", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n +  where 409 = <Response [409]>.status_code\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.)", "trace": "self = <test_create_courier.TestCreateCourier object at 0x000001BF44F43350>, create_courier_data = {'login': '67d64o9xdw', 'password': '0wr6yyo7wp'}, login_and_delete_courier = <Response [200]>\n\n    @allure.title('Проверка возвращаемого кода 409 при создании курьера с уже существующими данными')\n    def test_create_same_courier_data(self, create_courier_data, login_and_delete_courier):\n        payload = create_courier_data\n        response = requests.post(UrlData.url_create_courier, data=payload)\n>       assert response.status_code == 409 and response.json()[\"message\"] == ResponseBodyText.used_login\nE       AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE        +  where 409 = <Response [409]>.status_code\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.)\n\ntests\\test_create_courier.py:21: AssertionError"}, "start": 1707250099545, "stop": 1707250100006, "uuid": "e83170de-75c3-436d-a819-5940a6aafe7b", "historyId": "cbbc55ff1902e8e4133cab085137f5b9", "testCaseId": "cbbc55ff1902e8e4133cab085137f5b9", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_same_courier_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "ANDREY-LAPTOP"}, {"name": "thread", "value": "7944-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}