{"name": "Проверка возвращаемого кода 409 при создании курьера с уже существующими данными", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n +  where 409 = <Response [409]>.status_code\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.)", "trace": "self = <test_create_courier.TestCreateCourier object at 0x00000165D33C3CE0>, create_courier_data = {'login': 'u7v6cpmzkl', 'password': 'mn55hw90h3'}, login_and_delete_courier = <Response [200]>\n\n    @allure.title('Проверка возвращаемого кода 409 при создании курьера с уже существующими данными')\n    def test_create_same_courier_data(self, create_courier_data, login_and_delete_courier):\n        payload = create_courier_data\n        response = requests.post(UrlData.url_create_courier, data=payload)\n>       assert response.status_code == 409 and response.json()[\"message\"] == 'Этот логин уже используется'\nE       AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE        +  where 409 = <Response [409]>.status_code\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.)\n\ntests\\test_create_courier.py:27: AssertionError"}, "start": 1707158368794, "stop": 1707158369229, "uuid": "e01d6aba-57c6-4150-b047-17b2b7bbe146", "historyId": "cbbc55ff1902e8e4133cab085137f5b9", "testCaseId": "cbbc55ff1902e8e4133cab085137f5b9", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_same_courier_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "ANDREY-LAPTOP"}, {"name": "thread", "value": "9576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}